apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: node-demo
type: Opaque
stringData:
  POSTGRES_USER: PLACEHOLDER_POSTGRES_USER
  POSTGRES_PASSWORD: PLACEHOLDER_POSTGRES_PASSWORD
